/**
 * 定数定義
 * シート構成・ヘッダー・初期データ・色などをここで一元管理する。
 * セットアップ処理はすべてこの定義を読んでデータ駆動で動くため、
 * 列の追加・変更はまずこのファイルを修正する。
 */
import type { ChecklistItemDef, RuleSeed, SheetDef, SheetKey } from './types';

/** サンプルデータの識別マーク(備考列の先頭に付与し、削除機能で使用) */
export const SAMPLE_MARK = '【サンプル】';

/** 全社共通項目を表す店舗名 */
export const COMPANY_WIDE = '全社';

/** 色設定(直接コードに散らばらせず、ここで管理する) */
export const COLORS = {
  headerBg: '#1f4e79',
  headerFont: '#ffffff',
  sectionBg: '#d9e2f3',
  requiredBg: '#fff2cc',
  autoBg: '#efefef',
  danger: '#f4cccc',
  warning: '#fce5cd',
  ok: '#d9ead3',
  info: '#cfe2f3',
  dashboardTitle: '#1f4e79',
  band: '#f8f9fa',
};

/** シート定義(表示順 = この配列順) */
export const SHEETS: Record<SheetKey, SheetDef> = {
  DASHBOARD: {
    key: 'DASHBOARD',
    name: '01_経理ダッシュボード',
    headers: [],
    protect: true,
  },
  INTAKE: {
    key: 'INTAKE',
    name: '02_書類受付台帳',
    idPrefix: 'ACC',
    idWithMonth: true,
    headers: [
      '管理ID',
      '受付日',
      '対象年月',
      '書類発行日',
      '支払日',
      '支払期限',
      '対応期限',
      '法人・事業区分',
      '対象店舗',
      '部門',
      '書類種別',
      '書類名・内容',
      '発行元・取引先',
      '宛名',
      '金額',
      '消費税額',
      '支払方法',
      '支払元口座・カード',
      '勘定科目候補',
      '税区分候補',
      '税理士確認必要',
      'インボイス登録番号',
      '適格請求書確認',
      '経費計上月',
      '原本形式',
      '原本保管場所',
      'Google Driveリンク',
      'Gmailリンク',
      '関連URL',
      '受領者',
      '処理担当者',
      '確認者',
      '現在のステータス',
      '次の対応',
      '確認先',
      '重要度',
      '備考',
      '登録日時',
      '最終更新日時',
      '完了日',
      'データ不備フラグ',
      '不備内容',
    ],
    dateCols: ['受付日', '書類発行日', '支払日', '支払期限', '対応期限', '完了日'],
    datetimeCols: ['登録日時', '最終更新日時'],
    currencyCols: ['金額', '消費税額'],
    wrapCols: ['書類名・内容', '次の対応', '備考', '不備内容'],
    requiredCols: ['受付日', '法人・事業区分', '対象店舗', '書類種別', '書類名・内容'],
    autoCols: ['管理ID', '登録日時', '最終更新日時', '完了日'],
    validations: [
      { header: '法人・事業区分', settingsCategory: '法人・事業区分' },
      { header: '対象店舗', masterRef: { sheetKey: 'BUSINESS', header: '店舗名' } },
      { header: '書類種別', settingsCategory: '書類種別' },
      { header: '支払方法', settingsCategory: '支払方法' },
      { header: '税理士確認必要', checkbox: true },
      { header: '適格請求書確認', settingsCategory: '適格請求書確認' },
      { header: '原本形式', settingsCategory: '原本形式' },
      { header: '受領者', masterRef: { sheetKey: 'STAFF', header: '氏名' } },
      { header: '処理担当者', masterRef: { sheetKey: 'STAFF', header: '氏名' } },
      { header: '確認者', masterRef: { sheetKey: 'STAFF', header: '氏名' } },
      { header: '現在のステータス', settingsCategory: 'ステータス' },
      { header: '確認先', settingsCategory: '確認先' },
      { header: '重要度', settingsCategory: '重要度' },
      { header: 'データ不備フラグ', checkbox: true },
      { header: '発行元・取引先', masterRef: { sheetKey: 'VENDOR', header: '取引先名' } },
    ],
    logCols: [
      '金額',
      '消費税額',
      '支払日',
      '支払期限',
      '現在のステータス',
      'Google Driveリンク',
      '処理担当者',
      '確認者',
    ],
    notes: {
      管理ID: '自動採番されます(ACC-YYYYMM-0001)。手入力しないでください。',
      対象年月: '例: 2026-07。どの月の経費・売上に関係するか。',
      勘定科目候補: '経理担当者の候補です。最終判断は税理士が行います。',
      税区分候補: '候補です。最終判断は税理士が行います。',
      現在のステータス: '処理済みにすると完了日が自動入力されます。',
    },
  },
  RECEIPT: {
    key: 'RECEIPT',
    name: '03_レシート・領収書管理',
    idPrefix: 'RCT',
    idWithMonth: true,
    headers: [
      '管理ID',
      '利用日',
      '登録日',
      '法人・事業区分',
      '対象店舗',
      '利用者',
      '購入先',
      '内容',
      '利用目的',
      '金額',
      '支払方法',
      '使用カード・口座',
      '勘定科目候補',
      '税区分候補',
      '税理士確認必要',
      'インボイス有無',
      'インボイス登録番号',
      '原本・画像リンク',
      '原本保存状況',
      '会計ソフト入力状況',
      '入力日',
      '入力担当者',
      '確認状況',
      '不備内容',
      '重複判定キー',
      '重複候補',
      'ステータス',
      '登録日時',
      '更新日時',
      '備考',
    ],
    dateCols: ['利用日', '登録日', '入力日'],
    datetimeCols: ['登録日時', '更新日時'],
    currencyCols: ['金額'],
    wrapCols: ['内容', '利用目的', '不備内容', '備考'],
    requiredCols: ['利用日', '法人・事業区分', '対象店舗', '購入先', '金額'],
    autoCols: ['管理ID', '登録日', '重複判定キー', '重複候補', '登録日時', '更新日時', '入力日'],
    validations: [
      { header: '法人・事業区分', settingsCategory: '法人・事業区分' },
      { header: '対象店舗', masterRef: { sheetKey: 'BUSINESS', header: '店舗名' } },
      { header: '利用者', masterRef: { sheetKey: 'STAFF', header: '氏名' } },
      { header: '支払方法', settingsCategory: '支払方法' },
      { header: '税理士確認必要', checkbox: true },
      { header: 'インボイス有無', settingsCategory: 'インボイス有無' },
      { header: '原本保存状況', settingsCategory: '原本保存状況' },
      { header: '会計ソフト入力状況', settingsCategory: '会計ソフト入力状況' },
      { header: '入力担当者', masterRef: { sheetKey: 'STAFF', header: '氏名' } },
      { header: '確認状況', settingsCategory: 'ステータス' },
      { header: 'ステータス', settingsCategory: 'ステータス' },
    ],
    logCols: ['金額', 'ステータス', '原本・画像リンク', '会計ソフト入力状況', '原本保存状況'],
    notes: {
      重複判定キー: '利用日+購入先+金額+利用者 から自動生成。手入力不要。',
      重複候補: '同じ重複判定キーが他行にある場合 TRUE。条件付き書式で警告表示。',
      会計ソフト入力状況: '入力済みにすると入力日が自動入力されます。',
    },
  },
  INVOICE: {
    key: 'INVOICE',
    name: '04_請求書・支払管理',
    idPrefix: 'INV',
    idWithMonth: true,
    headers: [
      '管理ID',
      '請求書受領日',
      '請求日',
      '支払期限',
      '支払予定日',
      '支払完了日',
      '法人・事業区分',
      '対象店舗',
      '取引先',
      '請求内容',
      '請求金額',
      '消費税額',
      '支払方法',
      '支払口座',
      '振込手数料負担',
      '稟議・承認状況',
      '代表承認',
      '請求書リンク',
      '支払証明リンク',
      '会計ソフト入力状況',
      '支払状況',
      '担当者',
      '重要度',
      '税理士確認必要',
      '登録日時',
      '更新日時',
      '備考',
    ],
    dateCols: ['請求書受領日', '請求日', '支払期限', '支払予定日', '支払完了日'],
    datetimeCols: ['登録日時', '更新日時'],
    currencyCols: ['請求金額', '消費税額'],
    wrapCols: ['請求内容', '備考'],
    requiredCols: ['請求書受領日', '法人・事業区分', '対象店舗', '取引先', '請求金額', '支払期限'],
    autoCols: ['管理ID', '登録日時', '更新日時', '支払完了日'],
    validations: [
      { header: '法人・事業区分', settingsCategory: '法人・事業区分' },
      { header: '対象店舗', masterRef: { sheetKey: 'BUSINESS', header: '店舗名' } },
      { header: '取引先', masterRef: { sheetKey: 'VENDOR', header: '取引先名' } },
      { header: '支払方法', settingsCategory: '支払方法' },
      { header: '振込手数料負担', settingsCategory: '振込手数料負担' },
      { header: '稟議・承認状況', settingsCategory: '承認状況' },
      { header: '代表承認', settingsCategory: '承認状況' },
      { header: '会計ソフト入力状況', settingsCategory: '会計ソフト入力状況' },
      { header: '支払状況', settingsCategory: '支払状況' },
      { header: '担当者', masterRef: { sheetKey: 'STAFF', header: '氏名' } },
      { header: '重要度', settingsCategory: '重要度' },
      { header: '税理士確認必要', checkbox: true },
    ],
    logCols: [
      '請求金額',
      '消費税額',
      '支払予定日',
      '支払完了日',
      '支払状況',
      '代表承認',
      '請求書リンク',
      '支払証明リンク',
      '会計ソフト入力状況',
    ],
    notes: {
      支払状況: '支払済みにすると支払完了日が自動入力されます。',
      代表承認: '高額支払いは代表承認後に支払ってください(金額基準は運用マニュアル参照)。',
    },
  },
  CONTRACT: {
    key: 'CONTRACT',
    name: '05_契約書・重要書類管理',
    idPrefix: 'CTR',
    idWithMonth: true,
    headers: [
      '管理ID',
      '書類種別',
      '契約・書類名',
      '法人・事業区分',
      '対象店舗',
      '相手先',
      '契約開始日',
      '契約終了日',
      '自動更新有無',
      '解約通知期限',
      '更新確認日',
      '担当者',
      '保管場所',
      'Driveリンク',
      '原本保管有無',
      '重要事項',
      '更新・解約時の対応',
      'ステータス',
      '重要度',
      '登録日時',
      '更新日時',
      '備考',
    ],
    dateCols: ['契約開始日', '契約終了日', '解約通知期限', '更新確認日'],
    datetimeCols: ['登録日時', '更新日時'],
    wrapCols: ['重要事項', '更新・解約時の対応', '備考'],
    requiredCols: ['書類種別', '契約・書類名', '法人・事業区分', '相手先'],
    autoCols: ['管理ID', '登録日時', '更新日時'],
    validations: [
      { header: '書類種別', settingsCategory: '書類種別' },
      { header: '法人・事業区分', settingsCategory: '法人・事業区分' },
      { header: '対象店舗', masterRef: { sheetKey: 'BUSINESS', header: '店舗名' } },
      { header: '相手先', masterRef: { sheetKey: 'VENDOR', header: '取引先名' } },
      { header: '自動更新有無', settingsCategory: '自動更新有無' },
      { header: '担当者', masterRef: { sheetKey: 'STAFF', header: '氏名' } },
      { header: '原本保管有無', settingsCategory: '原本保存状況' },
      { header: 'ステータス', settingsCategory: 'ステータス' },
      { header: '重要度', settingsCategory: '重要度' },
    ],
    logCols: ['ステータス', 'Driveリンク', '契約終了日', '解約通知期限'],
    notes: {
      解約通知期限: 'この日までに解約通知しないと自動更新される契約は必ず入力してください。',
    },
  },
  RULE: {
    key: 'RULE',
    name: '06_書類処理ルール',
    idPrefix: 'RUL',
    idWithMonth: false,
    headers: [
      'ルールID',
      '書類カテゴリ',
      '書類の具体例',
      '受け取った直後にすること',
      'スプレッドシート登録先',
      '必須入力項目',
      '原本の保存方法',
      'Drive保存フォルダ',
      'ファイル名ルール',
      '誰に報告するか',
      '誰の承認が必要か',
      '税理士への共有有無',
      '社労士への共有有無',
      '会計ソフト入力有無',
      '処理期限',
      '処理完了の条件',
      '判断できない場合の対応',
      '税理士確認必要',
      '注意点',
      '関連マニュアルURL',
      '最終更新日',
      '更新者',
      '有効・無効',
    ],
    dateCols: ['最終更新日'],
    wrapCols: [
      '書類の具体例',
      '受け取った直後にすること',
      '必須入力項目',
      '処理完了の条件',
      '判断できない場合の対応',
      '注意点',
    ],
    autoCols: ['ルールID'],
    validations: [
      { header: '税理士確認必要', checkbox: true },
      { header: '有効・無効', settingsCategory: '有効・無効' },
      { header: '更新者', masterRef: { sheetKey: 'STAFF', header: '氏名' } },
    ],
    notes: {
      書類カテゴリ:
        '初期データは一般的な中小企業の運用を基準にした「初期案」です。自社の運用に合わせて修正し、税理士確認必要のチェックが付いた項目は必ず税理士に確認してください。',
    },
  },
  QUESTION: {
    key: 'QUESTION',
    name: '07_確認・質問管理',
    idPrefix: 'QST',
    idWithMonth: true,
    headers: [
      '質問ID',
      '登録日',
      '関連管理ID',
      '法人・事業区分',
      '対象店舗',
      '質問内容',
      '現在分かっている事実',
      '不明点',
      '確認先',
      '重要度',
      '回答期限',
      '回答内容',
      '回答者',
      '回答日',
      '今後の処理方法',
      'ルール化の要否',
      '書類処理ルールへの反映状況',
      'ステータス',
      '登録日時',
      '更新日時',
      '備考',
    ],
    dateCols: ['登録日', '回答期限', '回答日'],
    datetimeCols: ['登録日時', '更新日時'],
    wrapCols: ['質問内容', '現在分かっている事実', '不明点', '回答内容', '今後の処理方法', '備考'],
    requiredCols: ['質問内容', '確認先', '重要度'],
    autoCols: ['質問ID', '登録日', '回答日', '登録日時', '更新日時'],
    validations: [
      { header: '法人・事業区分', settingsCategory: '法人・事業区分' },
      { header: '対象店舗', masterRef: { sheetKey: 'BUSINESS', header: '店舗名' } },
      { header: '確認先', settingsCategory: '確認先' },
      { header: '重要度', settingsCategory: '重要度' },
      { header: 'ルール化の要否', settingsCategory: 'ルール化の要否' },
      { header: '書類処理ルールへの反映状況', settingsCategory: '反映状況' },
      { header: 'ステータス', settingsCategory: 'ステータス' },
    ],
    logCols: ['回答内容', 'ステータス'],
    notes: {
      ステータス: '処理済み(回答済み)にすると回答日が自動入力されます。',
      ルール化の要否: '「要」かつ反映状況が未反映のものはダッシュボードに表示されます。',
    },
  },
  MONTHLY_CLOSE: {
    key: 'MONTHLY_CLOSE',
    name: '08_月次締めチェックリスト',
    idPrefix: 'MCL',
    idWithMonth: true,
    headers: [
      'チェックID',
      '対象年月',
      'チェック項目',
      '対象店舗',
      '担当者',
      '期限',
      '実施状況',
      '完了日',
      '確認者',
      '証拠リンク',
      '問題・不足事項',
      '次の対応',
      '登録日時',
      '更新日時',
      '備考',
    ],
    dateCols: ['期限', '完了日'],
    datetimeCols: ['登録日時', '更新日時'],
    wrapCols: ['問題・不足事項', '次の対応', '備考'],
    autoCols: ['チェックID', '登録日時', '更新日時', '完了日'],
    validations: [
      { header: '対象店舗', masterRef: { sheetKey: 'BUSINESS', header: '店舗名' } },
      { header: '担当者', masterRef: { sheetKey: 'STAFF', header: '氏名' } },
      { header: '実施状況', settingsCategory: '実施状況' },
      { header: '確認者', masterRef: { sheetKey: 'STAFF', header: '氏名' } },
    ],
    logCols: ['実施状況'],
    notes: {
      実施状況: '完了にすると完了日が自動入力されます。',
    },
  },
  FIXED_COST: {
    key: 'FIXED_COST',
    name: '09_定期支払・固定費管理',
    idPrefix: 'FIX',
    idWithMonth: false,
    headers: [
      '管理ID',
      '法人・事業区分',
      '対象店舗',
      '費目',
      '支払先',
      '契約内容',
      '支払頻度',
      '通常金額',
      '支払日',
      '支払方法',
      '使用口座・カード',
      '契約書リンク',
      '請求書の取得方法',
      '担当者',
      '解約方法',
      '解約期限',
      '自動更新',
      'ステータス',
      '登録日時',
      '更新日時',
      '備考',
    ],
    currencyCols: ['通常金額'],
    datetimeCols: ['登録日時', '更新日時'],
    wrapCols: ['契約内容', '請求書の取得方法', '解約方法', '備考'],
    autoCols: ['管理ID', '登録日時', '更新日時'],
    validations: [
      { header: '法人・事業区分', settingsCategory: '法人・事業区分' },
      { header: '対象店舗', masterRef: { sheetKey: 'BUSINESS', header: '店舗名' } },
      { header: '費目', settingsCategory: '費目' },
      { header: '支払先', masterRef: { sheetKey: 'VENDOR', header: '取引先名' } },
      { header: '支払頻度', settingsCategory: '支払頻度' },
      { header: '支払方法', settingsCategory: '支払方法' },
      { header: '担当者', masterRef: { sheetKey: 'STAFF', header: '氏名' } },
      { header: '自動更新', settingsCategory: '自動更新有無' },
      { header: 'ステータス', settingsCategory: 'ステータス' },
    ],
    logCols: ['通常金額', 'ステータス'],
    notes: {
      支払日: '毎月の支払日(例: 27日)。数値または「月末」等で入力。',
    },
  },
  VENDOR: {
    key: 'VENDOR',
    name: '10_取引先マスター',
    idPrefix: 'VND',
    idWithMonth: false,
    headers: [
      '取引先ID',
      '取引先名',
      '取引内容',
      '担当者名',
      '電話番号',
      'メールアドレス',
      '法人番号',
      'インボイス登録番号',
      '通常の支払方法',
      '通常の勘定科目候補',
      '税区分候補',
      '対象店舗',
      '契約書リンク',
      '請求書取得方法',
      '有効・無効',
      '備考',
    ],
    wrapCols: ['取引内容', '請求書取得方法', '備考'],
    autoCols: ['取引先ID'],
    protect: true,
    validations: [
      { header: '通常の支払方法', settingsCategory: '支払方法' },
      { header: '対象店舗', masterRef: { sheetKey: 'BUSINESS', header: '店舗名' } },
      { header: '有効・無効', settingsCategory: '有効・無効' },
    ],
    notes: {
      通常の勘定科目候補: '候補です。最終判断は税理士が行います。',
    },
  },
  BUSINESS: {
    key: 'BUSINESS',
    name: '11_店舗・事業マスター',
    idPrefix: 'BUS',
    idWithMonth: false,
    headers: [
      '事業ID',
      '法人・個人事業区分',
      '法人・事業名',
      '店舗名',
      '店舗コード',
      '所在地',
      '管理責任者',
      '使用銀行口座',
      '使用クレジットカード',
      'Square店舗名',
      '会計上の部門名',
      '稼働状況',
      '備考',
    ],
    wrapCols: ['備考'],
    autoCols: ['事業ID'],
    protect: true,
    validations: [
      { header: '法人・個人事業区分', settingsCategory: '法人・事業区分' },
      { header: '稼働状況', settingsCategory: '稼働状況' },
    ],
    notes: {
      店舗名: '初期値は仮データです。実際の店舗名に書き換えてください(README参照)。',
      稼働状況: '稼働中の店舗のみ月次チェックリスト生成やプルダウンの対象になります。',
    },
  },
  STAFF: {
    key: 'STAFF',
    name: '12_担当者マスター',
    idPrefix: 'USR',
    idWithMonth: false,
    headers: [
      '担当者ID',
      '氏名',
      '役割',
      '所属店舗',
      'メールアドレス',
      '対応可能業務',
      '承認権限',
      '通知対象',
      '稼働状況',
      '備考',
    ],
    wrapCols: ['対応可能業務', '備考'],
    autoCols: ['担当者ID'],
    protect: true,
    validations: [
      { header: '役割', settingsCategory: '役割' },
      { header: '所属店舗', masterRef: { sheetKey: 'BUSINESS', header: '店舗名' } },
      { header: '承認権限', checkbox: true },
      { header: '通知対象', checkbox: true },
      { header: '稼働状況', settingsCategory: '稼働状況' },
    ],
    notes: {
      氏名: '初期値は仮データです。実際の担当者に書き換えてください。',
    },
  },
  SETTINGS: {
    key: 'SETTINGS',
    name: '13_設定・選択肢マスター',
    headers: ['カテゴリ', '設定値', '表示順', '有効'],
    protect: true,
    validations: [{ header: '有効', checkbox: true }],
    notes: {
      カテゴリ:
        '各シートのプルダウン候補を管理します。変更後はメニュー「入力規則を再設定」を実行してください。',
    },
  },
  CHANGE_LOG: {
    key: 'CHANGE_LOG',
    name: '14_変更履歴',
    idPrefix: 'CHG',
    idWithMonth: false,
    headers: [
      '変更ID',
      '変更日時',
      'シート名',
      '管理ID',
      '行番号',
      '変更した担当者',
      '変更した列',
      '変更前',
      '変更後',
      '操作種別',
      '備考',
    ],
    datetimeCols: ['変更日時'],
    protect: true,
  },
  SYSTEM_LOG: {
    key: 'SYSTEM_LOG',
    name: '15_システムログ',
    headers: [
      'ログ日時',
      'ログレベル',
      '処理名',
      'メッセージ',
      '対象シート',
      '対象管理ID',
      '実行ユーザー',
      'エラー詳細',
      '備考',
    ],
    datetimeCols: ['ログ日時'],
    protect: true,
  },
  ERROR_LIST: {
    key: 'ERROR_LIST',
    name: '16_エラー・不整合一覧',
    headers: [
      '検出日時',
      '不整合種別',
      '重要度',
      '対象シート',
      '管理ID',
      '問題内容',
      '修正方法',
      '担当者',
      '対応状況',
      '完了日',
    ],
    datetimeCols: ['検出日時'],
    dateCols: ['完了日'],
    wrapCols: ['問題内容', '修正方法'],
    validations: [
      { header: '担当者', masterRef: { sheetKey: 'STAFF', header: '氏名' } },
      { header: '対応状況', settingsCategory: '対応状況' },
    ],
  },
  FORM_INBOX: {
    key: 'FORM_INBOX',
    name: '90_フォーム受付(中間)',
    headers: [
      'タイムスタンプ',
      '登録者',
      '法人・事業区分',
      '対象店舗',
      '書類種別',
      '書類発行日',
      '購入先・発行元',
      '金額',
      '支払方法',
      '利用目的・書類内容',
      '書類画像またはファイル',
      '重要度',
      '備考',
      '取込状況',
      '取込先管理ID',
    ],
    notes: {
      取込状況: 'フォーム回答を02_書類受付台帳へ取り込んだ状態を記録します(自動)。',
    },
  },
};

/** シートの表示順 */
export const SHEET_ORDER: SheetKey[] = [
  'DASHBOARD',
  'INTAKE',
  'RECEIPT',
  'INVOICE',
  'CONTRACT',
  'RULE',
  'QUESTION',
  'MONTHLY_CLOSE',
  'FIXED_COST',
  'VENDOR',
  'BUSINESS',
  'STAFF',
  'SETTINGS',
  'CHANGE_LOG',
  'SYSTEM_LOG',
  'ERROR_LIST',
  'FORM_INBOX',
];

/** ステータス値(コード内で参照するもの) */
export const STATUS = {
  UNCONFIRMED: '未確認',
  TODO: '未処理',
  CHECKING: '内容確認中',
  IN_PROGRESS: '担当者対応中',
  WAIT_CEO: '代表確認待ち',
  WAIT_TAX: '税理士確認待ち',
  WAIT_LABOR: '社労士確認待ち',
  WAIT_VENDOR: '取引先回答待ち',
  WAIT_PAY: '支払待ち',
  WAIT_ENTRY: '会計入力待ち',
  WAIT_FILE: '原本保存待ち',
  DONE: '処理済み',
  NO_ACTION: '対応不要',
  HOLD: '保留',
  REJECTED: '差し戻し',
} as const;

export const PAY_STATUS = {
  UNPAID: '未払い',
  PLANNED: '支払予定',
  PROCESSING: '支払処理中',
  PAID: '支払済み',
  HOLD: '保留',
  NA: '対象外',
} as const;

export const ENTRY_STATUS = {
  TODO: '未入力',
  DOING: '入力中',
  DONE: '入力済み',
  NA: '対象外',
  CHECKING: '確認中',
} as const;

/** 未完了とみなすステータス(ダッシュボード・不整合検出で使用) */
export const OPEN_STATUSES: string[] = [
  STATUS.UNCONFIRMED,
  STATUS.TODO,
  STATUS.CHECKING,
  STATUS.IN_PROGRESS,
  STATUS.WAIT_CEO,
  STATUS.WAIT_TAX,
  STATUS.WAIT_LABOR,
  STATUS.WAIT_VENDOR,
  STATUS.WAIT_PAY,
  STATUS.WAIT_ENTRY,
  STATUS.WAIT_FILE,
  STATUS.REJECTED,
];

/** 13_設定・選択肢マスター 初期データ [カテゴリ, 設定値[]] */
export const SETTINGS_SEED: Array<[string, string[]]> = [
  [
    'ステータス',
    [
      '未確認',
      '未処理',
      '内容確認中',
      '担当者対応中',
      '代表確認待ち',
      '税理士確認待ち',
      '社労士確認待ち',
      '取引先回答待ち',
      '支払待ち',
      '会計入力待ち',
      '原本保存待ち',
      '処理済み',
      '対応不要',
      '保留',
      '差し戻し',
    ],
  ],
  ['重要度', ['緊急', '高', '中', '低']],
  ['法人・事業区分', ['法人', '個人事業', '判断不明']],
  ['原本形式', ['紙', 'PDF', '写真', 'メール', 'Web明細', 'その他']],
  [
    '支払方法',
    [
      '現金',
      '銀行振込',
      '口座振替',
      'クレジットカード',
      'デビットカード',
      '電子マネー',
      '個人立替',
      'その他',
    ],
  ],
  [
    '確認先',
    [
      '代表',
      '経理責任者',
      '税理士',
      '社労士',
      '行政書士',
      '銀行',
      '取引先',
      '店舗責任者',
      'その他',
    ],
  ],
  ['会計ソフト入力状況', ['未入力', '入力中', '入力済み', '対象外', '確認中']],
  ['支払状況', ['未払い', '支払予定', '支払処理中', '支払済み', '保留', '対象外']],
  [
    '書類種別',
    [
      'レシート',
      '領収書',
      '請求書',
      '見積書',
      '納品書',
      'クレジットカード明細',
      '銀行明細',
      '契約書',
      '業務委託契約書',
      '雇用関係書類',
      '給与関係書類',
      '社会保険関係書類',
      '労働保険関係書類',
      '税務書類',
      '行政書類',
      '融資関係書類',
      'リース関係書類',
      'Square関係書類',
      'ホットペッパービューティー関係書類',
      '楽天ビューティー関係書類',
      '売上資料',
      'その他',
    ],
  ],
  ['実施状況', ['未実施', '実施中', '完了', '対象外']],
  ['対応状況', ['未対応', '対応中', '対応済み', '解消済み', '対象外']],
  ['承認状況', ['不要', '未承認', '承認待ち', '承認済み', '差し戻し']],
  ['原本保存状況', ['未保存', '保存済み', '原本なし', '確認中']],
  ['インボイス有無', ['あり', 'なし', '不明']],
  ['適格請求書確認', ['未確認', '適格', '非適格', '対象外']],
  ['自動更新有無', ['あり', 'なし', '不明']],
  ['振込手数料負担', ['当方負担', '先方負担', '不明']],
  ['有効・無効', ['有効', '無効']],
  ['稼働状況', ['稼働中', '休止', '閉店', '退職']],
  ['支払頻度', ['毎月', '隔月', '四半期', '半年', '年1回', '不定期']],
  ['ルール化の要否', ['要', '不要', '検討中']],
  ['反映状況', ['未反映', '反映中', '反映済み', '対象外']],
  [
    '役割',
    ['代表', '経理責任者', '経理担当者', '店舗責任者', 'スタッフ', '税理士', '社労士', 'その他'],
  ],
  [
    '費目',
    [
      '家賃',
      '広告費',
      '水道光熱費',
      '通信費',
      'システム利用料',
      'リース料',
      '保険料',
      '税理士顧問料',
      '社労士顧問料',
      '清掃・タオル代',
      '材料仕入れ',
      'その他固定費',
    ],
  ],
];

/** 月次締めチェックリスト初期項目 */
export const CHECKLIST_ITEMS: ChecklistItemDef[] = [
  { item: '全店舗のレシート回収', scope: 'store', dueDay: 5 },
  { item: '全店舗の領収書回収', scope: 'store', dueDay: 5 },
  { item: 'クレジットカード明細確認', scope: 'company', dueDay: 10 },
  { item: '銀行明細確認', scope: 'company', dueDay: 10 },
  { item: 'Square売上確認', scope: 'store', dueDay: 7 },
  { item: 'ホットペッパー関係明細確認', scope: 'store', dueDay: 7 },
  { item: '楽天ビューティー関係明細確認', scope: 'store', dueDay: 7 },
  { item: '現金売上確認', scope: 'store', dueDay: 5 },
  { item: '未払い請求書確認', scope: 'company', dueDay: 10 },
  { item: '支払漏れ確認', scope: 'company', dueDay: 10 },
  { item: '会計ソフト入力確認', scope: 'company', dueDay: 15 },
  { item: '給与データ確認', scope: 'company', dueDay: 15 },
  { item: '業務委託報酬確認', scope: 'company', dueDay: 15 },
  { item: '税理士共有資料確認', scope: 'company', dueDay: 15 },
  { item: '原本未保存確認', scope: 'company', dueDay: 15 },
  { item: '不明取引の確認', scope: 'company', dueDay: 15 },
  { item: '店舗別損益資料の確認', scope: 'store', dueDay: 20 },
  { item: '月次資料のDrive保存', scope: 'company', dueDay: 20 },
  { item: '代表への月次報告', scope: 'company', dueDay: 20 },
  { item: '月次締め完了', scope: 'company', dueDay: 25 },
];

/** 06_書類処理ルール 初期データ(初期案。会社固有の内容は税理士確認必要フラグ付き) */
export const RULE_SEEDS: RuleSeed[] = [
  {
    category: 'レシート',
    examples: '材料購入、備品購入、飲食などのレシート',
    firstAction: '受付フォームまたは03_レシート・領収書管理へ登録し、写真を撮ってDriveへ保存',
    registerTo: '03_レシート・領収書管理',
    requiredFields: '利用日、店舗、購入先、金額、支払方法、利用目的',
    driveFolder: '01_レシート・領収書/YYYY/YYYY-MM/店舗名',
    deadline: '受領から3営業日以内に登録',
    taxCheck: '経費区分・勘定科目は税理士確認必要',
  },
  {
    category: '領収書',
    examples: '宛名入りの領収書',
    firstAction: '03_レシート・領収書管理へ登録し、原本を月別ファイルへ保管',
    registerTo: '03_レシート・領収書管理',
    requiredFields: '利用日、店舗、購入先、金額、宛名、インボイス登録番号',
    driveFolder: '01_レシート・領収書/YYYY/YYYY-MM/店舗名',
    deadline: '受領から3営業日以内に登録',
    taxCheck: 'インボイス要件の充足は税理士確認必要',
  },
  {
    category: 'クレジットカード利用明細',
    examples: '法人カード・個人カードの月次明細',
    firstAction: '04_銀行・カード明細フォルダへ保存し、02_書類受付台帳へ登録',
    driveFolder: '04_銀行・カード明細',
    deadline: '明細発行後5営業日以内',
    taxCheck: 'カード利用日と経費計上日の扱いは税理士確認必要',
  },
  {
    category: '銀行振込明細',
    examples: '振込受付書、入出金明細',
    firstAction: '04_銀行・カード明細フォルダへ保存し、支払証明として04_請求書・支払管理へリンク',
    driveFolder: '04_銀行・カード明細',
    deadline: '振込当日〜翌営業日',
  },
  {
    category: '請求書',
    examples: '取引先からの請求書(紙・PDF・メール)',
    firstAction: '04_請求書・支払管理へ登録し、支払期限と承認状況を必ず入力',
    registerTo: '04_請求書・支払管理',
    requiredFields: '受領日、取引先、金額、支払期限、支払方法',
    driveFolder: '02_請求書/YYYY/YYYY-MM',
    approver: '一定金額以上は代表(基準額は要設定)',
    deadline: '受領当日〜翌営業日に登録',
    taxCheck: '適格請求書の確認方法は税理士確認必要',
  },
  {
    category: '納品書',
    examples: '材料・商品の納品書',
    firstAction: '対応する請求書と突合し、02_書類受付台帳へ登録',
    deadline: '受領から3営業日以内',
  },
  {
    category: '見積書',
    examples: '工事・広告などの見積書',
    firstAction: '02_書類受付台帳へ登録し、発注判断は代表へ確認',
    reportTo: '代表',
    approver: '代表',
    accounting: 'なし',
  },
  {
    category: '契約書',
    examples: '賃貸借契約、取引基本契約など',
    firstAction: '05_契約書・重要書類管理へ登録し、原本は契約書ファイルへ保管',
    registerTo: '05_契約書・重要書類管理',
    requiredFields: '契約名、相手先、契約期間、自動更新有無、解約通知期限',
    driveFolder: '06_契約書',
    reportTo: '代表',
    approver: '代表',
    accounting: 'なし',
    caution: '解約通知期限は必ず登録する(自動更新トラブル防止)',
  },
  {
    category: '業務委託契約書',
    examples: '業務委託美容師との契約書',
    firstAction: '05_契約書・重要書類管理へ登録し、報酬条件を確認',
    registerTo: '05_契約書・重要書類管理',
    driveFolder: '06_契約書/業務委託',
    reportTo: '代表',
    approver: '代表',
    shareTax: 'あり(報酬・源泉の扱い)',
    taxCheck: '源泉徴収・消費税の扱いは税理士確認必要',
  },
  {
    category: '雇用関係書類',
    examples: '雇用契約書、労働条件通知書',
    firstAction: '05_契約書・重要書類管理へ登録し、社労士へ共有',
    registerTo: '05_契約書・重要書類管理',
    driveFolder: '06_契約書/雇用',
    shareLabor: 'あり',
    accounting: 'なし',
  },
  {
    category: '給与関係書類',
    examples: '給与明細、賃金台帳、源泉徴収簿',
    firstAction: '08_給与・報酬フォルダへ保存し、02_書類受付台帳へ登録',
    driveFolder: '08_給与・報酬',
    shareTax: 'あり',
    shareLabor: 'あり',
    taxCheck: '給与関連の計上方法は税理士確認必要',
  },
  {
    category: '社会保険関係書類',
    examples: '算定基礎届、標準報酬決定通知書',
    firstAction: '07_税務・行政/年金事務所へ保存し、社労士へ共有',
    driveFolder: '07_税務・行政/年金事務所',
    shareLabor: 'あり',
    deadline: '書類記載の期限に従う(受領当日に登録)',
  },
  {
    category: '労働保険関係書類',
    examples: '労働保険料申告書、概算・確定保険料通知',
    firstAction: '07_税務・行政へ保存し、社労士へ共有',
    driveFolder: '07_税務・行政/労働基準監督署',
    shareLabor: 'あり',
    deadline: '書類記載の期限に従う',
  },
  {
    category: '税務署からの書類',
    examples: '納付書、お知らせ、調査関係',
    firstAction: '開封当日に02_書類受付台帳へ登録し、税理士へ共有',
    driveFolder: '07_税務・行政/税務署',
    reportTo: '代表・税理士',
    shareTax: 'あり',
    deadline: '受領当日に登録(期限物が多い)',
    caution: '期限のある書類が多いため、対応期限を必ず入力する',
  },
  {
    category: '都税事務所からの書類',
    examples: '事業税・固定資産税(償却資産)関係',
    firstAction: '開封当日に登録し、税理士へ共有',
    driveFolder: '07_税務・行政/都税事務所',
    shareTax: 'あり',
    deadline: '受領当日に登録',
  },
  {
    category: '市役所からの書類',
    examples: '住民税特別徴収、各種通知',
    firstAction: '開封当日に登録し、内容に応じて税理士・社労士へ共有',
    driveFolder: '07_税務・行政/市役所',
    deadline: '受領当日に登録',
  },
  {
    category: '年金事務所からの書類',
    examples: '保険料納入告知書、調査通知',
    firstAction: '開封当日に登録し、社労士へ共有',
    driveFolder: '07_税務・行政/年金事務所',
    shareLabor: 'あり',
    deadline: '受領当日に登録',
  },
  {
    category: 'ハローワークからの書類',
    examples: '雇用保険関係、助成金関係',
    firstAction: '開封当日に登録し、社労士へ共有',
    driveFolder: '07_税務・行政/ハローワーク',
    shareLabor: 'あり',
  },
  {
    category: '労働基準監督署からの書類',
    examples: '是正勧告、調査通知、労災関係',
    firstAction: '開封当日に代表へ報告し、社労士へ共有',
    driveFolder: '07_税務・行政/労働基準監督署',
    reportTo: '代表',
    shareLabor: 'あり',
    caution: '重要度「緊急」で登録する',
  },
  {
    category: '保健所からの書類',
    examples: '営業許可、立入検査関係',
    firstAction: '開封当日に代表・店舗責任者へ報告',
    driveFolder: '07_税務・行政/保健所',
    reportTo: '代表・店舗責任者',
    accounting: 'なし',
  },
  {
    category: '銀行からの書類',
    examples: '残高証明、手数料改定通知など',
    firstAction: '02_書類受付台帳へ登録し、内容確認',
    driveFolder: '04_銀行・カード明細',
  },
  {
    category: '融資関係書類',
    examples: '金銭消費貸借契約、返済予定表',
    firstAction: '05_契約書・重要書類管理へ登録し、代表へ報告、税理士へ共有',
    registerTo: '05_契約書・重要書類管理',
    driveFolder: '06_契約書/その他',
    reportTo: '代表',
    shareTax: 'あり',
    taxCheck: '借入金・利息の計上は税理士確認必要',
  },
  {
    category: 'リース関係書類',
    examples: 'リース契約、リース料改定通知',
    firstAction: '05_契約書・重要書類管理と09_定期支払・固定費管理へ登録',
    registerTo: '05_契約書・重要書類管理',
    driveFolder: '06_契約書/その他',
    shareTax: 'あり',
    taxCheck: 'リースの会計処理は税理士確認必要',
  },
  {
    category: 'Square関係書類',
    examples: 'Square入金明細、手数料明細',
    firstAction: '05_売上資料/Squareへ保存し、月次締めで売上と突合',
    driveFolder: '05_売上資料/Square',
    shareTax: 'あり',
    taxCheck: 'Square売上の計上方法(総額/手数料控除)は税理士確認必要',
  },
  {
    category: 'ホットペッパービューティー関係書類',
    examples: '掲載料請求書、ポイント明細',
    firstAction: '05_売上資料/ホットペッパーへ保存し、請求書は04_請求書・支払管理へ登録',
    driveFolder: '05_売上資料/ホットペッパー',
    taxCheck: 'ポイント負担分の処理は税理士確認必要',
  },
  {
    category: '楽天ビューティー関係書類',
    examples: '利用明細、ポイント明細',
    firstAction: '05_売上資料/楽天ビューティーへ保存し、月次締めで突合',
    driveFolder: '05_売上資料/楽天ビューティー',
    taxCheck: '楽天ポイントの処理は税理士確認必要',
  },
  {
    category: '家賃・賃貸借関係',
    examples: '家賃請求、更新料通知、賃料改定',
    firstAction: '04_請求書・支払管理と09_定期支払・固定費管理を確認・更新',
    driveFolder: '06_契約書/店舗賃貸借',
    reportTo: '代表(改定・更新時)',
  },
  {
    category: '水道光熱費',
    examples: '電気・ガス・水道の請求・検針票',
    firstAction: '口座振替なら02_書類受付台帳へ登録、請求書払いなら04_請求書・支払管理へ',
    driveFolder: '02_請求書/YYYY/YYYY-MM',
  },
  {
    category: '通信費',
    examples: '携帯・ネット回線・電話の請求',
    firstAction: 'Web明細をPDF保存し、02_書類受付台帳へ登録',
    driveFolder: '02_請求書/YYYY/YYYY-MM',
  },
  {
    category: '広告費',
    examples: '広告掲載請求、Web広告明細',
    firstAction: '04_請求書・支払管理へ登録し、店舗別に按分が必要か確認',
    registerTo: '04_請求書・支払管理',
    driveFolder: '02_請求書/YYYY/YYYY-MM',
    taxCheck: '店舗間按分の方法は税理士確認必要',
  },
  {
    category: '材料・薬剤費',
    examples: 'カラー剤・パーマ剤などの仕入',
    firstAction: '納品書と請求書を突合し、04_請求書・支払管理へ登録',
    registerTo: '04_請求書・支払管理',
    driveFolder: '02_請求書/YYYY/YYYY-MM',
  },
  {
    category: '備品・消耗品費',
    examples: 'タオル、ドライヤー、事務用品など',
    firstAction: 'レシート・請求書に応じて03または04へ登録',
    taxCheck: '10万円以上は固定資産判定が必要(税理士確認必要)',
  },
  {
    category: '修繕費',
    examples: '店舗設備の修理・メンテナンス',
    firstAction: '04_請求書・支払管理へ登録',
    taxCheck: '修繕費と資本的支出の区分は税理士確認必要',
  },
  {
    category: '保険料',
    examples: '店舗総合保険、賠償責任保険など',
    firstAction: '09_定期支払・固定費管理へ登録し、証券は05_契約書・重要書類管理へ',
    driveFolder: '06_契約書/その他',
    taxCheck: '長期契約の前払処理は税理士確認必要',
  },
  {
    category: '税理士・社労士報酬',
    examples: '顧問料、決算料、手続き報酬の請求書',
    firstAction: '04_請求書・支払管理へ登録',
    driveFolder: '02_請求書/YYYY/YYYY-MM',
    taxCheck: '源泉徴収の要否は税理士確認必要',
  },
  {
    category: 'その他判断不明書類',
    examples: '分類が分からないすべての書類',
    firstAction:
      '00_未分類・新規受付へ保存し、02_書類受付台帳へ「判断不明」で登録、07_確認・質問管理へ質問を起票',
    registerTo: '02_書類受付台帳',
    whenUnsure: '07_確認・質問管理へ登録し、経理責任者→代表の順に確認',
    caution: '捨てない・放置しない。必ず台帳に載せる。',
  },
];

/** Google Drive フォルダ構成 */
export const DRIVE_FOLDER_TREE: string[] = [
  '00_未分類・新規受付',
  '01_レシート・領収書',
  '02_請求書',
  '03_支払証明',
  '04_銀行・カード明細',
  '05_売上資料/Square',
  '05_売上資料/ホットペッパー',
  '05_売上資料/楽天ビューティー',
  '06_契約書/店舗賃貸借',
  '06_契約書/業務委託',
  '06_契約書/雇用',
  '06_契約書/広告',
  '06_契約書/システム',
  '06_契約書/その他',
  '07_税務・行政/税務署',
  '07_税務・行政/都税事務所',
  '07_税務・行政/市役所',
  '07_税務・行政/年金事務所',
  '07_税務・行政/ハローワーク',
  '07_税務・行政/労働基準監督署',
  '07_税務・行政/保健所',
  '08_給与・報酬',
  '09_税理士共有',
  '10_月次締め',
  '99_保管・過年度',
];

/** ルール未指定時のデフォルト値 */
export const RULE_DEFAULTS = {
  registerTo: '02_書類受付台帳',
  requiredFields: '受付日、法人・事業区分、対象店舗、書類種別、内容、金額',
  originalStorage: '原本は月別ファイルに保管し、スキャン(写真)をDriveへ保存',
  reportTo: '経理責任者',
  approver: '経理責任者',
  shareTax: '月次共有時にまとめて',
  shareLabor: 'なし',
  accounting: 'あり',
  deadline: '受領から5営業日以内',
  doneCondition: '台帳登録・Drive保存・会計ソフト入力・原本保管がすべて完了',
  whenUnsure: '07_確認・質問管理へ登録し、経理責任者へ確認',
  fileNameRule: 'YYYYMMDD_法人または店舗名_取引先_書類種別_金額_管理ID',
};
